[package]
name = "mdx"
version = "0.5.0"
edition = "2024"
description = "MDict .mdx/.mdd file reader and writer for Rust"
license = "GNU Affero General Public License v3.0"
repository = "https://github.com/raymanzhang/mdx"
keywords = [
    "mdict",
    "mdx",
    "mdd",
    "dictionary",
    "reader",
    "writer",
    "parser",
    "serialization",
]
categories = [
    "encoding",
    "parser-implementations",
]
readme = "README.md"
authors = ["Rayman Zhang <raymanzhang@gmail.com>"]
homepage = "https://github.com/raymanzhang/mdx"
documentation = "https://github.com/raymanzhang/mdx/blob/main/README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["icu"]
rust-icu = ["dep:rust_icu_ucol", "dep:rust_icu_common", "dep:rust_icu_ustring"]
icu = ["dep:icu", "dep:icu_collator", "dep:icu_locale", "dep:icu_provider"]

[dependencies]
snafu = { version = "^0.8", features = ["backtrace"] }
log = "^0.4.27"
env_logger = "^0.11.8"
lz4 = "^1.24"
lzma-rs = "^0.3"
bzip2 = "^0.6.0"
rust-lzo = "^0.6.2"
rand = "^0.9.0"
serde = { version = "^1.0.215", features = ["derive"] }
adler = "^1.0"
serde-xml-rs = "^0.8.1"
serde_json = "^1.0.140"
xxhash-rust = { version = "^0.8.15", features = ["xxh64"] }
byteorder = "^1.5.0"
lru = "^0.16.0"
once_cell = "^1.21.3"
lazy_static = "^1.5.0"
flate2 = "^1.1.2"
hex = "^0.4.3"
url = "^2.5.2"
percent-encoding = "^2.3.0"
indexmap = "^2.9.0"
encoding_rs = "^0.8.35"
bytemuck = "^1.23.1"
quick-xml = "^0.38.0"
regex = "^1.11.1"
ripemd128 = "^0.1.2"
uuid = { version = "^1.17.0", features = ["v4"] }
chrono = "^0.4.41"
lol_html = "^2.6.0"
tantivy = "^0.25.0"
zip = { version = "6.0.0", default-features = false, features = ["deflate"] }
walkdir = "^2.4.0"
shellexpand = "^3.1.0"
mime_guess = "^2.0.0"
htmlescape = "0.3.1"

# ICU dependencies - made optional through features
icu = { version = "^2.0.0", optional = true }
icu_collator = { version = "^2.0.0", optional = true }
icu_locale = { version = "^2.0.0", optional = true }
icu_provider = { version = "^2.0.0", optional = true }

[target.'cfg(not(target_os = "windows"))'.dependencies]
rust_icu_sys = { version="5.0.0", optional = true }
rust_icu_ucol = { version = "^5.0.0", optional = true }
rust_icu_common = { version = "^5.0.0", optional = true }
rust_icu_ustring = { version = "^5.0.0", optional = true }

[target.x86_64-pc-windows-gnu.dependencies]
rust_icu_sys = { version="5.0.0", default-features = false, features=["renaming", "icu_version_in_env"], optional = true }
rust_icu_ucol = { version = "^5.0.0", default-features = false, features = [
    "renaming",
    "icu_version_in_env",
], optional = true }
rust_icu_common = { version = "^5.0.0", default-features = false, features = [
    "renaming",
    "icu_version_in_env",
], optional = true }
rust_icu_ustring = { version = "^5.0.0", default-features = false, features = [
    "renaming",
    "icu_version_in_env",
], optional = true }
